name: myapp
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" 

dependencies:
  flutter:
    sdk: flutter


  dio: ^5.7.0
  path_provider: ^2.1.4
  flutter_pdfview: ^1.3.4
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  file_picker: ^8.1.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  camera: ^0.11.0
  permission_handler: ^11.3.1
  firebase_database: ^11.1.4
  flutter_local_notifications: ^17.2.4
  intl: ^0.19.0
  timezone: ^0.9.4
  shared_preferences: ^2.3.2
  http: ^1.2.2
 


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/welcomepage.png
    - images/loginpage.png
    - images/clinic.png




